anse-app/chatgpt-demo

src/components/MessageItem.tsx
=> fix: do not shrink the avatar

src/components/Generator.tsx
- native tool tip for clear icon
- turn off auto complete
- auto focus in input element
close: #6 
close: #7
=> feat: native tool tip for clear icon and experience optimization

src/components/Generator.tsx
=> feat: support line breaks in input

src/components/Generator.tsx
Automatically scroll the page to the bottom.
=> feat: automatically scroll the page to the bottom

src/components/Generator.tsx
Add a padding for scrollable `textarea`.
close: #78 
Source of inspiration: https://twitter.com/pacocoursey/status/1630425455235940352, THX.
=> feat: padding for scrollable textarea

src/components/Generator.tsx
=> reset textarea height when clear

.env.example, src/components/Generator.tsx, src/pages/api/generate.ts, src/utils/auth.ts
Add signature verification to the API request to prevent abuse.
- Allow customizing `PUBLIC_SECRET_KEY` in environment variables
- Signature validity period: 5 minutes.
None
- Signature algorithms are still not secure enough.
=> feat: add signature verification

package.json, pnpm-lock.yaml, src/components/MessageItem.tsx
Add copy code block feature, close #69 .
=> feat: add copy code block feature

src/components/MessageItem.tsx
Fix copy blank space undefined bug.
https://github.com/ddiu8081/chatgpt-demo/pull/86#issuecomment-1457316268
=> fix: copy blank space undefined bug

src/components/MessageItem.tsx
@ddiu8081  GPT replies to HTML answers are usually in two forms, one in Markdown form and one in plain text, and if you want to handle this plain text form of HTML, you may be able to render it, provided that you feel it is feasible.
#127
=> feat: add render html

README.md, astro.config.mjs, netlify.toml, package.json, pnpm-lock.yaml, vercel.json
=> feat: add netlify support

src/utils/auth.ts
=> fix: ReferenceError: crypto is not defined

src/components/Themetoggle.astro
Fix the issue that the page does not initialize with the last theme selection from local storage when opened.
Fixes #187
=> fix: init theme

.env.example, astro.config.mjs, package.json, pnpm-lock.yaml, src/components/Generator.tsx, src/components/Themetoggle.astro, src/layouts/Layout.astro, src/pages/api/auth.ts, src/pages/api/generate.ts, src/pages/api/password_auth.ts, src/pages/index.astro, src/pages/password.astro
Add site password verification to avoid unauthorized access.
- Add an environment variable `SITE_PASSWORD`.
- Validate on every request to `generate` API, and on every entry to the site.
#149
=> Feature: site password

src/components/MessageItem.tsx
=> fix: change copy button bg in light theme

.vscode/extensions.json, astro.config.mjs, package.json, pnpm-lock.yaml, src/components/Footer.astro, src/components/Generator.tsx, src/components/Header.astro, src/components/MessageItem.tsx, src/components/SystemRoleSettings.tsx, src/pages/password.astro, unocss.config.ts
1. remove the `lodash` package, because `solidjs-use·`has fully met the needs of development, there is no need to increase the package size.
2. use `unocss shortcuts` to simplify css code.
3.  fix the problem that the background color splashes when the copy button switches the theme color.
=> chore: optimize some code

dockerfile
we can set custom host and port in `env`:
https://www.npmjs.com/package/@astrojs/node#user-content-custom-host-and-port
=> feat: better dockerfile

src/components/BackTop.astro, src/pages/index.astro, unocss.config.ts
=> feat: add backTop button

README.md, docker-compose.yml
Adding a docker-compose.yml file to facilitate deployment with Docker.
=> feat: add docker-compose.yml

README.md, README.zh-CN.md
add `SITE_PASSWORD` environment variables for vercel deploy and netlify deploy.
=> feat: add SITE_PASSWORD for Vercel deploy and Netlify deploy

astro.config.mjs
Improved astro.config.mjs
Improved config file following VSCode indications
=> Improved astro.config.mjs

src/components/Themetoggle.astro
style change: toggle theme button add bounce animation
=> style: toggle theme button add bounce animation

.env.example, README.md, README.zh-CN.md, src/pages/api/auth.ts, src/pages/api/generate.ts
- `SITE_PASSWORD` env support multiple password separated by comma
- Compatible with previously created passwords containing commas
- none
=> feat: support multiple password separated by comma.

src/components/Send.tsx
Feat:v2 Add the function of sending messages by hitting enter.
=> Feat:v2 Add the function of sending messages by hitting enter.

astro.config.mjs, package.json, plugins/disableBlocks.ts, pnpm-lock.yaml, src/components/Themetoggle.astro, src/layouts/Layout.astro
Now Netlify also supports PWA features. I have updated the dependencies and tested it, without causing any issues.
#418
=> fix: allow PWA in netlify

.github/workflows/lint.yml, Dockerfile
Lint Action ask for a later pnpm version, so update it to the latest version.(https://github.com/zhullyb/chatgpt-demo/actions/runs/6824331758)
For Docker image build action, I test it on my personal computer, all we need to do is to copy resources first and then run `pnpm install`.(https://github.com/zhullyb/chatgpt-demo/actions/runs/6824229219/job/18559704164)
https://github.com/anse-app/chatgpt-demo/issues/445
https://github.com/anse-app/chatgpt-demo/issues/436
=> fix for github action
